# netlify.toml

# Build settings
[build]
  base = "Frontend"
  command = "npm run build"
  publish = "Frontend/build"
  functions = "Frontend/netlify/functions"

# Deploy log visibility
log = "public"

# Build status
ignore = false
